config/routes.rb
Rails.application.routes.draw do
  resources :captions
  resources :videos
  resources :playlists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/caption.rb
class Caption < ApplicationRecord
  belongs_to :video
  scope :query, ->(query) {
    words = query.split(',')
    search_sql = []

    words = words.map do |word|
        search_sql.push('lower(text) LIKE ?')
        "%#{word.downcase}%"
    end

    where( search_sql.join(' or '), *words )
  }
end

app/models/playlist.rb
class Playlist < ApplicationRecord
	has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :playlist
  has_many :captions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/captions_controller.rb
class CaptionsController < ApplicationController
  before_action :set_caption, only: %i[ show edit update destroy ]

  # GET /captions or /captions.json
  def index
    if params[:query] and (params[:query] != '')
      @captions = Caption.query(params[:query].downcase).reverse_order#.limit(16)
    else
      @captions = Caption.all.reverse_order.limit(512)
    end
  end

  # GET /captions/1 or /captions/1.json
  def show
  end

  # GET /captions/new
  def new
    @caption = Caption.new
  end

  # GET /captions/1/edit
  def edit
  end

  # POST /captions or /captions.json
  def create
    @caption = Caption.new(caption_params)

    respond_to do |format|
      if @caption.save
        format.html { redirect_to caption_url(@caption), notice: "Caption was successfully created." }
        format.json { render :show, status: :created, location: @caption }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /captions/1 or /captions/1.json
  def update
    respond_to do |format|
      if @caption.update(caption_params)
        format.html { redirect_to caption_url(@caption), notice: "Caption was successfully updated." }
        format.json { render :show, status: :ok, location: @caption }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /captions/1 or /captions/1.json
  def destroy
    @caption.destroy

    respond_to do |format|
      format.html { redirect_to captions_url, notice: "Caption was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caption
      @caption = Caption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caption_params
      params.require(:caption).permit(:text, :timestamp, :video_id, :query)
    end
end

app/controllers/playlists_controller.rb
Yt.configuration.api_key = ENV['GOOGLE_API_KEY'] 
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    ytpl = Yt::Playlist.new id: playlist_params[:web_id]
    # require 'pry'
    # binding.pry
    ytpl.playlist_items.map do |video|
      @playlist.videos << Video.new(web_id: video.video_id, playlist_id: @playlist.id)
    end

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      @playlist.videos.each do |video|
        begin
          cmd = `youtube_transcript_api --format json #{video.web_id}`
          captions = JSON.parse(cmd)[0]
        rescue => error
          p error.message
          next
        end
        captions.each do |caption|
          video.captions << Caption.new(text: caption['text'], timestamp: caption['start'], video_id: video.id)
        end
      end
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:web_id)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:web_id, :playlist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captions_helper.rb
module CaptionsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/captions/_caption.html.erb
<div id="<%= dom_id caption %>">
  <p>
    <strong>Text:</strong>
    <%= caption.text %>
  </p>

  <p>
    <strong>Timestamp:</strong>
    <%= caption.timestamp %>
  </p>

  <p>
    <strong>Video:</strong>
    <%= caption.video_id %>
  </p>

  <iframe id="ytplayer_<%= caption.video.web_id %>" type="text/html"
  src="https://www.youtube.com/embed/<%= caption.video.web_id %>?start=<%= caption.timestamp.to_i %>&origin=localhost&cc_load_policy=1"
  frameborder="0"></iframe>

</div>

app/views/captions/_form.html.erb
<%= form_with(model: caption) do |form| %>
  <% if caption.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(caption.errors.count, "error") %> prohibited this caption from being saved:</h2>

      <ul>
        <% caption.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :timestamp, style: "display: block" %>
    <%= form.text_field :timestamp %>
  </div>

  <div>
    <%= form.label :video_id, style: "display: block" %>
    <%= form.text_field :video_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/captions/edit.html.erb
<h1>Editing caption</h1>

<%= render "form", caption: @caption %>

<br>

<div>
  <%= link_to "Show this caption", @caption %> |
  <%= link_to "Back to captions", captions_path %>
</div>

app/views/captions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Captions</h1>

<div id="captions">
  <% @captions.each do |caption| %>
    <%= render caption %>
    <p>
      <%= link_to "Show this caption", caption %>
    </p>
  <% end %>
</div>

<%= link_to "New caption", new_caption_path %>

app/views/captions/new.html.erb
<h1>New caption</h1>

<%= render "form", caption: @caption %>

<br>

<div>
  <%= link_to "Back to captions", captions_path %>
</div>

app/views/captions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @caption %>

<div>
  <%= link_to "Edit this caption", edit_caption_path(@caption) %> |
  <%= link_to "Back to captions", captions_path %>

  <%= button_to "Destroy this caption", @caption, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Captionly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :web_id, style: "display: block" %>
    <%= form.text_field :web_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p>
    <strong>Web:</strong>
    <%= playlist.web_id %>
  </p>

</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Playlists</h1>

<div id="playlists">
  <% @playlists.each do |playlist| %>
    <%= render playlist %>
    <p>
      <%= link_to "Show this playlist", playlist %>
    </p>
  <% end %>
</div>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playlist %>

<div>
  <%= link_to "Edit this playlist", edit_playlist_path(@playlist) %> |
  <%= link_to "Back to playlists", playlists_path %>

  <%= button_to "Destroy this playlist", @playlist, method: :delete %>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :web_id, style: "display: block" %>
    <%= form.text_field :web_id %>
  </div>

  <div>
    <%= form.label :playlist_id, style: "display: block" %>
    <%= form.text_field :playlist_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <p>
    <strong>Web:</strong>
    <%= video.web_id %>
  </p>

  <p>
    <strong>Playlist:</strong>
    <%= video.playlist_id %>
  </p>

</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Show this video", @video %> |
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Videos</h1>

<div id="videos">
  <% @videos.each do |video| %>
    <%= render video %>
    <p>
      <%= link_to "Show this video", video %>
    </p>
  <% end %>
</div>

<%= link_to "New video", new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @video %>

<div>
  <%= link_to "Edit this video", edit_video_path(@video) %> |
  <%= link_to "Back to videos", videos_path %>

  <%= button_to "Destroy this video", @video, method: :delete %>
</div>